name = "GenSNA"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Gen-SNA Contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gen = "e5f0d0b3-2f52-4d0c-8598-72c3f4a7a1bc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
julia = "1.9"
Gen = "0.4"
DataFrames = "1"
CSV = "0.10"
Plots = "1"
StatsPlots = "0.15"
